name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy using Docker Compose
        run: |
          docker-compose -f docker/docker-compose.yml down
          docker-compose -f docker/docker-compose.yml up -d --build
